apiVersion: apps/v1
kind: Deployment
metadata:
  name: beneficiary-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: beneficiary-service
  template:
    metadata:
      labels:
        app: beneficiary-service
    spec:
      containers:
        - name: beneficiary-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
