apiVersion: v1
kind: Service
metadata:
  name: beneficiary-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: beneficiary-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
